# Generated by Django 2.0.5 on 2018-05-20 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='date_add_data',
            new_name='date_added',
        ),
    ]
